version: "3.9"  # optional since v1.27.0
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: fabian08
  admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fabian0896@outlook.com
      PGADMIN_DEFAULT_PASSWORD: fabian08